language: go
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ameyamahajani6757/ameya .
    - docker images
    - docker push ameyamahajani6757/ameya
