language: go
dist: trusty
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ameya/hello-webpage .
    - docker images
    - docker push ameya/hello-webpage
  
