language: go
dist: trusty
jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ameyamahajani6757/ameya .
    - docker images
    - docker push ameyamahajani6757/ameya
  - stage: Deploy to Heroku
    deploy:
      provider: heroku
      api_key:
        secure: ilVoKZM04Ke7pH4Vf1PdTMC+x8LyViDHy9BSWiHTtXBLY9iwHwzHHrlrY6uSkXxEwX9L6hLZ90PU1yOzayuBB1lZ6zu0HGABxedhBHcKjBZhbpkh9WwClwVrzsx3PO+eX1wLBCY1kW7AbqMU1YZPKMEgDneCT2Goe4+vEE36QebnJMYBDqZVAmt5PHjtIQLvvoay40XjxJSdLYXb2EGsdsdYeMUzvEmC7EQeuXur826sehQy7S6OBqtlx4/4x8tsFLZgczvIeqiPdHJT1QwS8NlsGNnvWK91BPe4XWBrMIgM4fZn1L80usYHPKzF+SeU0hKXfwGPSyoc+KKK61bCHE1SXI1L5c4zfPT7UrIQlQlvNMSpyXhbBDF25clLLm6zoRvqsZ/N5LZO/eoRa9aWvjQymXVVMWVScx3eiI9+T9TQiPmN/ueZ8KrQ4C2HFSjlgpUJyaVIsUOwwSJpC+E8evXKbs/K38a3yFXH77l8PsUoxp3Lnv78aoGGOX6Y77TaEl0ut6SsEZBWHTjsSo+laAx64sWsHXaUz1lTtrZkWub6pgOTc0VTwMR2FRylDBN5AlEAjb2ppXntcW7Uk0p8ieBOvwK7CR5+AwjRBUXY9j60dABPh/vQxWVCQI6759TH2MHmjMOAT0YFWT5Dbn8BXDF9trrQt2A2Hi4HMZ/hDaw=
        app: my-webapp6757
      on:
        repo: inajaham-ayema-6757/Docker-tutorial
