language: go
dist: trusty
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t inajaham-ayema-6757/Docker-tutorial .
    - docker images
    - docker push inajaham-ayema-6757/Docker-tutorial
  
